### ISSUE TITLE
error after deployed to heroku

### ISSUE THREAD

**Issue by bugbounted** [MatheusGatti/Instagram-Bot-for-Repost#2]
Hi [Matheus](https://github.com/MatheusGatti),
I'm trying to deploy this repo to heroku but after deployed get error below in dyno runtime log :

2022-05-12T17:26:24.968718+00:00 app[api]: Enable Logplex by user sarinazar@protonmail.com
2022-05-12T17:26:24.968718+00:00 app[api]: Release v2 created by user sarinazar@protonmail.com
2022-05-12T17:26:25.373330+00:00 app[api]: Upgrade stack to heroku-20 by user sarinazar@protonmail.com
2022-05-12T17:26:25.373330+00:00 app[api]: Release v3 created by user sarinazar@protonmail.com
2022-05-12T17:26:26.000000+00:00 app[api]: Build started by user sarinazar@protonmail.com
2022-05-12T17:26:56.588472+00:00 app[api]: Deploy by user sarinazar@protonmail.com
2022-05-12T17:26:56.588472+00:00 app[api]: Release v4 created by user sarinazar@protonmail.com
2022-05-12T17:27:08.000000+00:00 app[api]: Build succeeded
2022-05-12T17:27:58.903171+00:00 app[api]: Scaled to worker@1:Free by user sarinazar@protonmail.com
2022-05-12T17:28:04.422283+00:00 heroku[worker.1]: Starting process with command `python App.py`
2022-05-12T17:28:05.004970+00:00 heroku[worker.1]: State changed from starting to up
2022-05-12T17:28:06.081969+00:00 app[worker.1]: Status 429: Too many requests
2022-05-12T17:28:06.082064+00:00 app[worker.1]: Ignore 429: Continue login
2022-05-12T17:28:12.848829+00:00 app[worker.1]: Entrando no Instagram...
2022-05-12T17:28:12.848870+00:00 app[worker.1]: Perfis cadastrados: 1
2022-05-12T17:28:12.848873+00:00 app[worker.1]: Timer zerado, procurando novas postagens...
2022-05-12T17:28:12.848874+00:00 app[worker.1]: Procurando no perfil @resturan_gardi_tehran
2022-05-12T17:28:23.481617+00:00 app[worker.1]: Tipo de mídia identificada: igtv
2022-05-12T17:28:32.725221+00:00 heroku[worker.1]: State changed from up to crashed
2022-05-12T17:28:32.730428+00:00 heroku[worker.1]: State changed from crashed to starting
2022-05-12T17:28:32.447970+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-12T17:28:32.447986+00:00 app[worker.1]:   File "/app/App.py", line 178, in <module>
2022-05-12T17:28:32.448153+00:00 app[worker.1]:     mediaPath = salvarMedia(cl, mediaTipo, objPostagem.pk)
2022-05-12T17:28:32.448165+00:00 app[worker.1]:   File "/app/App.py", line 66, in salvarMedia
2022-05-12T17:28:32.448276+00:00 app[worker.1]:     mediaPath = cl.igtv_download(media_pk, 'media_temp')
2022-05-12T17:28:32.448285+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/instagrapi/mixins/igtv.py", line 41, in igtv_download
2022-05-12T17:28:32.448364+00:00 app[worker.1]:     return self.video_download(media_pk, folder)
2022-05-12T17:28:32.448372+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/instagrapi/mixins/video.py", line 60, in video_download
2022-05-12T17:28:32.448445+00:00 app[worker.1]:     return self.video_download_by_url(media.video_url, filename, folder)
2022-05-12T17:28:32.448453+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/instagrapi/mixins/video.py", line 94, in video_download_by_url
2022-05-12T17:28:32.448520+00:00 app[worker.1]:     with open(path, "wb") as f:
2022-05-12T17:28:32.448548+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'media_temp/resturan_gardi_tehran_2836619801026107489.mp4'
2022-05-12T17:28:32.639568+00:00 heroku[worker.1]: Process exited with status 1
2022-05-12T17:28:36.376847+00:00 heroku[worker.1]: Starting process with command `python App.py`
2022-05-12T17:28:37.454372+00:00 heroku[worker.1]: State changed from starting to up
2022-05-12T17:28:38.270239+00:00 app[worker.1]: Status 429: Too many requests
2022-05-12T17:28:38.270323+00:00 app[worker.1]: Ignore 429: Continue login
2022-05-12T17:28:43.989485+00:00 app[worker.1]: Entrando no Instagram...
2022-05-12T17:28:43.989505+00:00 app[worker.1]: Perfis cadastrados: 1
2022-05-12T17:28:43.989506+00:00 app[worker.1]: Timer zerado, procurando novas postagens...
2022-05-12T17:28:43.989507+00:00 app[worker.1]: Procurando no perfil @resturan_gardi_tehran
2022-05-12T17:28:54.882016+00:00 app[worker.1]: Tipo de mídia identificada: igtv
2022-05-12T17:29:04.430380+00:00 heroku[worker.1]: State changed from up to crashed
2022-05-12T17:29:04.364980+00:00 heroku[worker.1]: Process exited with status 1
2022-05-12T17:29:04.203248+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-12T17:29:04.203261+00:00 app[worker.1]:   File "/app/App.py", line 178, in <module>
2022-05-12T17:29:04.203409+00:00 app[worker.1]:     mediaPath = salvarMedia(cl, mediaTipo, objPostagem.pk)
2022-05-12T17:29:04.203418+00:00 app[worker.1]:   File "/app/App.py", line 66, in salvarMedia
2022-05-12T17:29:04.203510+00:00 app[worker.1]:     mediaPath = cl.igtv_download(media_pk, 'media_temp')
2022-05-12T17:29:04.203521+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/instagrapi/mixins/igtv.py", line 41, in igtv_download
2022-05-12T17:29:04.203590+00:00 app[worker.1]:     return self.video_download(media_pk, folder)
2022-05-12T17:29:04.203598+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/instagrapi/mixins/video.py", line 60, in video_download
2022-05-12T17:29:04.203657+00:00 app[worker.1]:     return self.video_download_by_url(media.video_url, filename, folder)
2022-05-12T17:29:04.203665+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/instagrapi/mixins/video.py", line 94, in video_download_by_url
2022-05-12T17:29:04.203727+00:00 app[worker.1]:     with open(path, "wb") as f:
2022-05-12T17:29:04.203757+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'media_temp/resturan_gardi_tehran_2836619801026107489.mp4'

please fix it
waiting for your response
finest regards

**Comment by pmbeman** [comment]
it's playwright problem , please change this part of page to puppeteer .
waiting for your commits
finest regards

**Comment by MatheusGatti** [comment]
I guess this error is because Heroku don't support for saving files like the media of post feed, video etc.
